version: '3'

services:
  client:
    restart: always
    build: .
    ports:
      - 3000:3000
    networks:
      - my-network 
    volumes:
      - ./:/app 
      - /app/node_modules/
      - /app/.next/
    depends_on:
      - api
    env_file:
      - .env.local
  mongo:
    image: mongo
    volumes:
      - mongo-store:/data/db
    networks:
      - my-network 
  api:
    restart: always
    build: ../code-library-server
    ports:
      - 4000:4000
    volumes:
      - ../code-library-server/:/app
    networks:
      - my-network
    depends_on:
      - mongo

volumes:
  mongo-store:

networks:
  my-network:
    driver: bridge