version: '3'

services:
  api:
    restart: always
    build:
      context: ../code-library-server
      target: development
    container_name: app_backend
    volumes:
      - ../code-library-server:/app
    networks:
      - codelibrary_network
    ports:
      - 4000:4000
    env_file:
      - .env.local
    depends_on:
      - mongo

volumes:
  mongo-store:

networks:
  codelibrary_network:
