version: '3'

services:
  mongo:
    image: mongo
    container_name: app_db
    ports:
      - 27017:27017
    volumes:
      - mongo-store:/data/db
    networks:
      - codelibrary_network
  api:
    restart: always
    image: gcr.io/code-library-343215/code-library-api:latest
    container_name: app_backend
    networks:
      - codelibrary_network
    ports:
      - 4000:4000
    env_file:
      - .env.local
    depends_on:
      - mongo

volumes:
  mongo-store:

networks:
  codelibrary_network:
