version: '3'

services:
  # app:
  #   build:
  #     context: .
  #     target: testing
  #   env_file: .env.local
  #   # entrypoint: 'node .next/standalone/server.js'
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - codelibrary_network

  mongo:
    image: mongo
    container_name: app_db
    ports:
      - 27017:27017
    volumes:
      - mongo-store:/data/db
    networks:
      - codelibrary_network
  # api:
  #   restart: always
  #   container_name: app_backend
  #   networks:
  #     - codelibrary_network
  #   ports:
  #     - 4000:4000
  #   env_file:
  #     - .env.local
  #   depends_on:
  #     - mongo

volumes:
  mongo-store:

networks:
  codelibrary_network:
