version: '3'

services:
  proxy:
    image: caddy:latest
    container_name: app_proxy
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/openssl/certs:/etc/caddy/certs
    networks:
      codelibrary_network:
        aliases:
          - "api.codelibrary.dev"
          - "client.codelibrary.dev"
    extra_hosts:
      - "api.codelibrary.dev:127.0.0.1"
      - "client.codelibrary.dev:127.0.0.1"
    ports:
      - "80:80"
      - "443:443"
  client:
    build:
      context: .
      target: development
    restart: always
    container_name: app_client
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    networks:
      - codelibrary_network
    depends_on:
      - api
    environment:
      - APP_ENV=docker
    env_file:
      - .env.local
  mongo:
    image: mongo
    container_name: app_db
    volumes:
      - mongo-store:/data/db
    networks:
      - codelibrary_network
  api:
    restart: always
    image: gcr.io/code-library-343215/code-library-api:latest
    container_name: app_backend
    networks:
      - codelibrary_network
    ports:
      - 4000:4000
    env_file:
      - .env.local
      - .env.backend
    depends_on:
      - mongo

volumes:
  mongo-store:

networks:
  codelibrary_network:
