import type { NextApiRequest } from "next";
import type { NextRequest } from "next/server";
import type { JWT } from "next-auth/jwt";
import jwt from "jsonwebtoken";

function signToken(tokenData: any) {
  return jwt.sign(tokenData, process.env.JWT_SECRET);
}
function verifyToken(tokenStr: unknown) {
  if (typeof tokenStr !== "string") return null;

  try {
    return jwt.verify(tokenStr, process.env.JWT_SECRET) as JWT;
  } catch (err) {
    return null;
  }
}
function tokenFromRequest(req: NextRequest | NextApiRequest) {
  /* 
  for some fucking reason the name of the jwt cookie generated by next-auth changes in production.
  next-auth themselves are probably not at fault, as this breaks their own getToken function
  */
  const cookieName =
    process.env.NODE_ENV === "production"
      ? "__Secure-next-auth.session-token"
      : "next-auth.session-token";

  const tokenStr = req.cookies[cookieName];

  return verifyToken(tokenStr);
}
export { signToken, verifyToken, tokenFromRequest };
