name: Build of The Library App UI

on: [push]

jobs:
  build-container:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Publish Container
        env:
          IMAGE_NAME: code-library-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --tag $IMAGE_NAME:$IMAGE_TAG --build-arg NEXT_PUBLIC_GRAPHQL_URL=${{ secrets.NEXT_PUBLIC_GRAPHQL_URL }} .
