name: Build & Tests

on:
  push:
    branches: ['main']
  workflow_dispatch: # Allow manual invocation of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:ci
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        env:
          IMAGE_NAME: code-library-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --tag $IMAGE_NAME:$IMAGE_TAG --build-arg NEXT_PUBLIC_CLIENT_URL=${{ secrets.NEXT_PUBLIC_CLIENT_URL }} .
